/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:0d045a42ced784fa5dee48127aca4b6f:057d63649978c04d80eb33f7d2f6df7b:04fed8a2b1d878d119f113aa1b353fec$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class FullSprite
	{
		public const string IdleLeft = "IdleLeft";
		public const string IdleRight = "IdleRight";
		public const string RunLeft = "RunLeft";
		public const string RunRight = "RunRight";
	}
}